<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="DotNetSeleniumExtras.PageObjects.Core" Version="4.14.1" />
	  <PackageReference Include="DotNetSeleniumExtras.PageObjects.Core.Linq" Version="1.0.0" />
	</ItemGroup>

</Project>
